name: taskly

networks:
  default_network:
    driver: bridge

volumes:
  elastic-data:
    driver: local
  todos-db-data:
    driver: local
  keycloak-db-data:
    driver: local

services:
  # ---------------------------
  # OpenTelemetry Collector
  # ---------------------------
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    container_name: otel-collector
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    networks:
      - default_network
  
  # ---------------------------
  # Zipkin for Traces
  # ---------------------------
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - default_network
  
  # ---------------------------
  # Elasticsearch for Logs
  # ---------------------------
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1" ]
    networks:
      - default_network
  
  # ---------------------------
  # Kibana for Log Visualization
  # ---------------------------
  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - default_network
    depends_on:
      elasticsearch:
        condition: service_healthy
  
  # ---------------------------
  # Prometheus for Metrics
  # ---------------------------
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--web.enable-remote-write-receiver"  # Enable remote write receiver
    ports:
      - "9090:9090"
    networks:
      - default_network

  # ---------------------------
  # Grafana for Metrics Visualization
  # ---------------------------
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - default_network
  
  # ---------------------------
  # Todos API Database
  # ---------------------------
  todos-db:
    image: postgres
    container_name: todos-db
    environment:
      - POSTGRES_USER=${TODOS_DB_USER}
      - POSTGRES_PASSWORD=${TODOS_DB_PASSWORD}
      - POSTGRES_DB=${TODOS_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - todos-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${TODOS_DB_USER}" ]
    networks:
      - default_network
  
  # ---------------------------
  # Todos API
  # ---------------------------
  todos-api:
    build:
      context: ../
      dockerfile: ./.docker/dockerfiles/TodosApi.Dockerfile
    container_name: todos-api
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - ConnectionStrings__TodosDb=${TODOS_DB_CONNECTION_STRING}
      - ASPNET
    depends_on:
      todos-db:
        condition: service_healthy
    networks:
      - default_network
  
  # ---------------------------
  # Gateway
  # ---------------------------
  gateway:
    build:
      context: ../
      dockerfile: ./.docker/dockerfiles/Gateway.Dockerfile
    container_name: gateway
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    ports:
      - "8080:8080"
    networks:
      - default_network
  
  # ---------------------------
  # Keycloak Database
  # ---------------------------
  keycloak-db:
    image: postgres
    container_name: keycloak-db
    environment:
      - POSTGRES_DB=${KC_DB_NAME}
      - POSTGRES_USER=${KC_DB_USERNAME}
      - POSTGRES_PASSWORD=${KC_DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${KC_DB_USERNAME}" ]
    networks:
      - default_network
  
  # ---------------------------
  # Keycloak
  # ---------------------------
  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: keycloak
    command: [ "start-dev" ]
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak-db:5432/${KC_DB_NAME}
      - KC_DB_USERNAME=${KC_DB_USERNAME}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KC_ADMIN_USERNAME}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KC_ADMIN_PASSWORD}
    ports:
      - "8081:8080"
    networks:
      - default_network
    depends_on:
      keycloak-db:
        condition: service_healthy