receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  debug:
    verbosity: detailed
  
  prometheusremotewrite:
    endpoint: "http://prometheus:9090/api/v1/write"
  
  otlphttp:
    endpoint: http://seq/ingest/otlp

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ ]
      exporters: [ debug, otlphttp ]
    metrics:
      receivers: [ otlp ]
      processors: [ ]
      exporters: [ debug, prometheusremotewrite ]
    logs:
      receivers: [ otlp ]
      processors: [ ]
      exporters: [ debug, otlphttp ]